// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0a3JB_bsdBIR9qNJM0XwuOtyrPbcTp6Q',
    appId: '1:687190283967:web:53de75708d75f517e6d80a',
    messagingSenderId: '687190283967',
    projectId: 'flutter-firebase-tutoria-fd27c',
    authDomain: 'flutter-firebase-tutoria-fd27c.firebaseapp.com',
    storageBucket: 'flutter-firebase-tutoria-fd27c.appspot.com',
    measurementId: 'G-0J5M02TT97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVGgFgW9UeOezYWyH0M4GTctufFf2c_Hc',
    appId: '1:687190283967:android:3dfa87ac22429adfe6d80a',
    messagingSenderId: '687190283967',
    projectId: 'flutter-firebase-tutoria-fd27c',
    storageBucket: 'flutter-firebase-tutoria-fd27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6e-IDT37drFC9DUDVCgTByMAW0yZFl40',
    appId: '1:687190283967:ios:d219564e31debfd1e6d80a',
    messagingSenderId: '687190283967',
    projectId: 'flutter-firebase-tutoria-fd27c',
    storageBucket: 'flutter-firebase-tutoria-fd27c.appspot.com',
    iosClientId: '687190283967-u59aoq8h1p3fsmp8m3luu64f4seq43hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6e-IDT37drFC9DUDVCgTByMAW0yZFl40',
    appId: '1:687190283967:ios:d219564e31debfd1e6d80a',
    messagingSenderId: '687190283967',
    projectId: 'flutter-firebase-tutoria-fd27c',
    storageBucket: 'flutter-firebase-tutoria-fd27c.appspot.com',
    iosClientId: '687190283967-u59aoq8h1p3fsmp8m3luu64f4seq43hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );
}
